baseURL = "https://imageu.github.io/"
languageCode = "en-us"
title = "ImageU (Image Understaning)"
theme = "vanilla-bootstrap-hugo-theme"
#googleAnalytics = "UA-123456789-1"

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "News"
    pre = "coffee"
    url = "/news/"
    weight = 2
  [[menu.nav]]
    name = "Projects"
    pre = "box"
    url = "/projects/"
    weight = 3
  [[menu.nav]]
    name = "Data&Code"
    pre = "database"
    url = "/data+code/"
    weight = 4
  [[menu.nav]]
    name = "Members"
    pre = "users"
    url = "/members/"
    weight = 5
  # [[menu.nav]]
  #   name = "About"
  #   pre = "info"
  #   url = "/about/"
  #   weight = 6

[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Image Understanding project home page"
  footerText = "Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = false